test conditional jobs

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,38 +1,18 @@
-name: github actions testing
+name: Conditional Job Example
 
-on:
-  push:
-  workflow_dispatch:
+on: [push]
 
 jobs:
-  tests:
-    timeout-minutes: 20
+  job1:
     runs-on: ubuntu-latest
-
     steps:
-      - uses: actions/checkout@v4
+      - name: Simulate failure
+        run: exit 1 # This simulates a failure
 
-      - name: get patch new digest
-        id: parse_diff
-        run: |
-          # echo "digest=$(git diff HEAD~ | grep +vllm | grep sha256 | cut -d @ -f 2 )" | tee --append $GITHUB_OUTPUT
-
-          # testing only:
-          echo "digest=$(cat patch.diff | grep +vllm | grep sha256 | cut -d @ -f 2 )" | tee --append $GITHUB_OUTPUT
-
-      - name: tag info
-        id: validate_digest
-        continue-on-error: true
-        run: |
-          echo "parsed digest: ${{ steps.parse_diff.outputs.digest }}"
-          python validate_digest.py ${{ steps.parse_diff.outputs.digest }}
-
-      - name: Close PR on failure
-        if: ${{ steps.validate_digest.outcome == 'failure'}}
-        run: |
-          echo "Closing PR: it corresponds to a non-CUDA build"
-
-      - name: Merge PR on success
-        if: ${{ steps.validate_digest.outcome == 'success'}}
-        run: |
-          echo "Merging PR"
+  job2:
+    runs-on: ubuntu-latest
+    needs: [job1]
+    if: failure()
+    steps:
+      - name: Handle failure
+        run: echo "job1 failed"
