test skopeo install/inspect

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,6 +24,11 @@ jobs:
           ]
 
     steps:
-      - uses: actions/checkout@v4
-        with:
-          repository: deepseek-ai/DeepGEMM
+      - name: "setup skopeo"
+        run: |
+          sudo apt install -y skopeo
+
+      - name: "inspect"
+        run: |
+          repo=quay.io/vllm/automation-vllm:0.10.1.1.1_rocm634
+          skopeo inspect --no-tags docker://$repo || echo "Repository cannot be found or user is not authorized: $repo"
