gha: test continue-on-error

diff --git a/.github/workflows/package.yml b/.github/workflows/package.yml
--- a/.github/workflows/package.yml
+++ b/.github/workflows/package.yml
@@ -10,21 +10,37 @@ jobs:
     strategy:
       matrix:
         # os: [macos-latest, windows-latest, ubuntu-latest]
-        os: [windows-latest]
+        os: [ubuntu-latest]
         # python-version: ["3.8", "3.9", "3.10"]
         python-version: ["3.8"]
       fail-fast: true
 
     steps:
       - uses: actions/checkout@v2
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v2
+      # - name: Set up Python ${{ matrix.python-version }}
+      #   uses: actions/setup-python@v2
+      #   with:
+      #     python-version: ${{ matrix.python-version }}
+      # - name: Install dependencies
+      #   run: |
+      #     python -m pip install --upgrade pip setuptools wheel
+      #     pip install docker pywin32>=302
+      # - name: Run
+      #   run: |
+      #     python testing.py
+      - name: failure
+        id: failing
+        continue-on-error: true
+        run: |
+          exit 1
+
+      - name: status
+        run: |
+          echo "conclusion: "${{ steps.failing.conclusion }}
+
+      - name: "Notify failure"
+        if: ${{ steps.failing.conclusion != 'success' }}
+        uses: actions/github-script@v3
         with:
-          python-version: ${{ matrix.python-version }}
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip setuptools wheel
-          pip install docker pywin32>=302
-      - name: Run
-        run: |
-          python testing.py
+          script: |
+            core.warning('Session failed')
